config/routes.rb
TicketsEverywhere::Application.routes.draw do
  devise_for :admins do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end

  resources :tickets do
    get :filter, on: :collection
    resources :comments
  end

  root :to => 'tickets#new'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :admin_id
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :email, :issue, :name, :description, :status, :subject, :unique_reference,
                  :admin_id

  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }
  validates :subject, presence: true, length: { maximum: 70 }
  validates :description, presence: true, length: { minimum: 30 }

  extend FriendlyId
  friendly_id :unique_reference

  belongs_to :admin

  has_many :comments, dependent: :destroy

  def self.search(search)
    if search
      find(:all, conditions: ['name LIKE ? OR unique_reference LIKE ? OR description LIKE ?', 
                              "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @ticket = Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.create(params[:comment])
    
    if @comment.save
      if @comment.admin_id
        # TicketConfirmationMailer.ticket_updated(@ticket, @comment).deliver
        @ticket.update_attributes(status: 'Waiting for Customer', admin_id: @comment.admin_id)
      else
        @ticket.update_attributes(status: 'Waiting for Staff Response')
      end
      redirect_to ticket_path(@ticket)
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :require_login,     only: [:index, :edit, :update]

  def index
    @tickets = Ticket.paginate(page: params[:page]).search(params[:search])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
      if current_admin
        @id = current_admin.id
      end

      params[:ticket][:admin_id] = @id
      if @ticket.update_attributes(params[:ticket])
        flash[:success] = 'Ticket was successfully updated.'
        redirect_to @ticket
      else
        render 'edit'
      end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def new
    @ticket = Ticket.new
  end

  def create
    # Check if there are records in Database and depending on results
    # create unique reference for a ticket
    @ticket_check = Ticket.first

    if @ticket_check.blank?
      @unique_reference = 'AAA-000001'
    else
      @unique_reference = next_reference(Ticket.last.unique_reference)
    end

    params[:ticket][:unique_reference] = @unique_reference

    @ticket = Ticket.new(params[:ticket])
      if @ticket.save
        # Send confirmation email
        # TicketConfirmationMailer.ticket_submittion(@ticket).deliver
        redirect_to @ticket
        flash[:success] = "Ticket was successfully created!"
      else
        render 'new'
      end
  end

  def filter
    @tickets = Ticket.paginate(page: params[:page]).where("status = ?", params[:condition])
    render 'index'
  end

  private

  # Makes unique reference increase starting with AAA-000001 till ZZZ-999999
  def next_reference(reference, limit = 6, seperator = '-')
    if reference[/[0-9]+\z/] == ?9 * limit
      "#{reference[/\A[a-z]+/i].next}#{seperator}#{?0 * (limit - 1)}1"
    else
      reference.next
    end
  end

  def require_login
    unless current_admin
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 50)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{href: "https://github.com/Razix/tickets_everywhere"} Issue tracker
    by Bogdan Rykhlitskyy

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "New ticket", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          - if admin_signed_in?
            %li= link_to "Tickets", tickets_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{href: '#', "data-toggle" => "dropdown"}
                Admin panel 
                %b.caret
              %ul.dropdown-menu
                %li= link_to "New unassigned tickets", action: :filter, |
                              condition: "Waiting for Staff Response"
                %li= link_to "Open Tickets", action: :filter, condition: "Waiting for Customer"
                %li= link_to "On hold tickets", action: :filter, condition: "On Hold Ticket"
                %li= link_to "Closed Tickets", action: :filter, condition: "Closed Ticket"
                %br/
                %form{action: tickets_path, method: "get"}
                  = text_field_tag(:search, params[:search])
                  = submit_tag("Search", name: nil, class: "btn btn-large btn-primary search_btn")
                %li.divider
                %li= link_to "Sign out", destroy_admin_session_path, method: :delete
          - else
            %li= link_to "Sign up", new_admin_registration_path
            %li= link_to "Sign in", new_admin_session_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ src: "http://html5shim.googlecode.com/svn/trunk/html5.js" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield(:title)
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = render 'layouts/footer'
      %br/
      %br/
      = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
    - object.errors.full_messages.each do |msg|
      %li.submit_errors
        #{msg}

app/views/tickets/_edit_form.html.haml
= render 'shared/error_messages', object: f.object
%br/
= f.label :name
= f.text_field :name

= f.label :email
= f.text_field :email

= f.label :issue
= f.select :issue, [['General','general'],['Account','account'],['Billing','billing'],['Technical','technical']]

= f.label :status
= f.select :status, [['Waiting for Staff Response','New unassigned ticket'], ['Waiting for Customer','Open Ticket'], ['On Hold','On Hold Ticket'], ['Cancelled','Closed Ticket'], ['Completed','Closed Ticket']]

= f.label :subject
= f.text_field :subject

= f.label :description
= f.text_area :description

app/views/tickets/_fields.html.haml
= render 'shared/error_messages', object: f.object
%br/
= f.label :name
= f.text_field :name

= f.label :email
= f.text_field :email

= f.label :issue
= f.select :issue, [['General','general'],['Account','account'],    |
                   ['Billing','billing'],['Technical','technical']] |

= f.label :subject
= f.text_field :subject

= f.label :description
= f.text_area :description, rows: "10"

= f.hidden_field :status, value: "Waiting for Staff Response"

app/views/tickets/edit.html.haml
- provide(:title, 'Edit ticket')
%h1 Edit ticket

.row
  .span6.offset3
    = form_for(@ticket) do |f|
      = render 'edit_form', f: f
      = f.submit "Update information", class: "btn btn-large btn-primary"

app/views/tickets/index.html.haml
- provide(:title, 'Tickets list')
%h1 All existing tickets

= will_paginate

.row
  .span6.offset3
    %table
      %tr
        %td.headers.subject
          %i Subject
        %td.headers
          %i Action
      - @tickets.each do |ticket|
        %tr
          %td.ticket_subject
            = link_to ticket.subject, ticket
          %td
            = link_to 'Edit', edit_ticket_path(ticket)

= will_paginate

app/views/tickets/new.html.haml
- provide(:title, 'New request')
%h1 Please submit your request
.row
  .span6.offset3
    = form_for(@ticket) do |f|
      = render 'fields', f: f
      = f.submit "Submit request", class: "btn btn-large btn-primary"

app/views/tickets/show.html.haml
- provide(:title, 'Check ticket')
%h1 Ticket #{@ticket.unique_reference}

.row
  .span6.offset3
    %p#notice= notice
    %p
      %b Reporter name:
      = @ticket.name
    %p
      %b Reporter email:
      = @ticket.email
    %p
      %b Issue type:
      = @ticket.issue
    %p
      %b Subject:
      = @ticket.subject
    %p
      %b Description:
      = wrap(@ticket.description)
    %br/

    %h2 Replies:
    -if !@ticket.comments.empty?
      - @ticket.comments.each do |comment|
        %p
          -if comment.admin_id
            %hr/
            %span.content= wrap(comment.body)
            %span.timestamp Posted #{time_ago_in_words(comment.created_at)} ago
            %br/
            by staff member
            %b
              %i #{Admin.where(id: comment.admin_id).first.email}
          -else
            %hr/
            %span.content= wrap(comment.body)
            %span.timestamp Posted #{time_ago_in_words(comment.created_at)} ago
            %br/
            by ticket reporter
            %b
              %i #{@ticket.name}
    -else
      %b
        %i No replies yet ;(  
    %br/    

    %h2 Add your reply:
    = form_for([@ticket, @ticket.comments.build]) do |f|
      %p
        - if current_admin
          - id = current_admin.id
          = f.hidden_field :admin_id, {value: id}
        = f.text_area :body
      = f.submit "Post comment", class: "btn btn-large btn-primary"